import{a as d,i as m,S as f}from"./assets/vendor-044cfab3.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();d.defaults.headers.common["x-api-key"]="live_xHKc8FIBjkm1E18PddbFIzDWm1A3cqdNob17m8SynQtgQRslGe43lBLgRPbecUZK";async function p(){return(await d.get("https://api.thecatapi.com/v1/breeds")).data}async function y(e){return(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`)).data}const i=document.querySelector(".breed-select"),a=document.querySelector(".loader"),l=document.querySelector(".cat-info"),h=document.querySelector(".error");h.classList.add("is-hidden");i.classList.add("is-hidden");async function g(){try{const e=await p();b(e),i.style.display="flex",v()}catch(e){u(`${e}! Breeds error`)}finally{a.classList.add("is-hidden"),i.classList.remove("is-hidden")}}document.addEventListener("DOMContentLoaded",g);i.addEventListener("change",L);function b(e){const n=e.map(({id:r,name:o})=>`<option value="${r}">${o}</option>`).join("");i.innerHTML=`<select class="breed-select ss-main" id="selectElem">${n}</select>`}async function L(e){console.dir(e.currentTarget),a.classList.remove("is-hidden"),e.preventDefault();const n=e.currentTarget.value;try{await y(n).then(r=>{l.style.display="flex";const o=`
                <img class="cat-img" src="${r[0].url}" alt="${r[0].breeds[0].alt_names}" />
                <div class="breed-info">
                  <h1 class="cat-name">${r[0].breeds[0].name}</h1>
                      <p class="description">${r[0].breeds[0].description}</p>
                      <h2 class="temperament">Temperament:</h2>
                      <p class="temp-descr">${r[0].breeds[0].temperament}</p>
                </div>
              `;l.innerHTML=o})}catch(r){u(`${r}! Cat by breed error`)}finally{a.classList.add("is-hidden")}}function v(){new f({select:".breed-select",settings:{placeholderText:"Search breeds"}})}function u(e){l.innerHTML="",i.style.display="none",m.error({message:`${e} fetching information! Try again!`,position:"topLeft"})}
//# sourceMappingURL=commonHelpers.js.map
